package edu.colorado.cires.cruisepack.app.ui.controller;

public final class Events {

  // Package
  public static final String UPDATE_CRUISE_ID = "UPDATE_CRUISE_ID";
  public static final String UPDATE_CRUISE_ID_ERROR = "UPDATE_CRUISE_ID_ERROR";
  public static final String UPDATE_SEA = "UPDATE_SEA";
  public static final String UPDATE_ARRIVAL_PORT = "UPDATE_ARRIVAL_PORT";
  public static final String UPDATE_DEPARTURE_PORT = "UPDATE_DEPARTURE_PORT";
  public static final String UPDATE_SHIP = "UPDATE_SHIP";
  public static final String UPDATE_SEGMENT = "UPDATE_SEGMENT";
  public static final String UPDATE_SEGMENT_ERROR = "UPDATE_SEGMENT_ERROR";
  public static final String UPDATE_DEPARTURE_DATE = "UPDATE_DEPARTURE_DATE";
  public static final String UPDATE_DEPARTURE_DATE_ERROR = "UPDATE_DEPARTURE_DATE_ERROR";
  public static final String UPDATE_ARRIVAL_DATE = "UPDATE_ARRIVAL_DATE";
  public static final String UPDATE_ARRIVAL_DATE_ERROR = "UPDATE_ARRIVAL_DATE_ERROR";
  public static final String UPDATE_RELEASE_DATE = "UPDATE_RELEASE_DATE";
  public static final String UPDATE_RELEASE_DATE_ERROR = "UPDATE_RELEASE_DATE_ERROR";
  public static final String UPDATE_PACKAGE_DIRECTORY = "UPDATE_PACKAGE_DIRECTORY";
  public static final String UPDATE_PACKAGE_DIRECTORY_ERROR = "UPDATE_PACKAGE_DIRECTORY_ERROR";
  public static final String UPDATE_SEA_ERROR = "UPDATE_SEA_ERROR";
  public static final String UPDATE_ARRIVAL_PORT_ERROR = "UPDATE_ARRIVAL_PORT_ERROR";
  public static final String UPDATE_DEPARTURE_PORT_ERROR = "UPDATE_DEPARTURE_PORT_ERROR";
  public static final String UPDATE_SHIP_ERROR = "UPDATE_SHIP_ERROR";

  // Footer Control
  public static final String UPDATE_STOP_BUTTON_ENABLED = "UPDATE_STOP_BUTTON_ENABLED";
  public static final String UPDATE_SAVE_BUTTON_ENABLED = "UPDATE_SAVE_BUTTON_ENABLED";
  public static final String UPDATE_PACKAGE_BUTTON_ENABLED = "UPDATE_PACKAGE_BUTTON_ENABLED";


  // PeopleModel
  public static final String UPDATE_SCIENTISTS = "UPDATE_SCIENTISTS";
  public static final String UPDATE_SOURCE_ORGANIZATIONS = "UPDATE_SOURCE_ORGANIZATIONS";
  public static final String UPDATE_FUNDING_ORGANIZATIONS = "UPDATE_FUNDING_ORGANIZATIONS";
  public static final String UPDATE_METADATA_AUTHOR = "UPDATE_METADATA_AUTHOR";
  // Errors
  public static final String UPDATE_SCIENTIST_ERROR = "UPDATE_SCIENTIST_ERROR";
  public static final String UPDATE_SOURCE_ORGANIZATION_ERROR = "UPDATE_SOURCE_ORGANIZATION_ERROR";
  public static final String UPDATE_FUNDING_ORGANIZATION_ERROR = "UPDATE_FUNDING_ORGANIZATION_ERROR";
  public static final String UPDATE_METADATA_AUTHOR_ERROR = "UPDATE_METADATA_AUTHOR_ERROR";

  // OmicsModel
  public static final String UPDATE_OMICS_SAMPLING_CONDUCTED = "UPDATE_OMICS_SAMPLING_CONDUCTED";
  public static final String UPDATE_OMICS_CONTACT = "UPDATE_OMICS_CONTACT";
  public static final String UPDATE_OMICS_SAMPLE_TRACKING_SHEET = "UPDATE_OMICS_SAMPLE_TRACKING_SHEET";
  public static final String UPDATE_OMICS_BIO_PROJECT_ACCESSION = "UPDATE_OMICS_BIO_PROJECT_ACCESSION";
  public static final String UPDATE_OMICS_WATER_SAMPLING_TYPE = "UPDATE_OMICS_WATER_SAMPLING_TYPE";
  public static final String UPDATE_OMICS_SOIL_SEDIMENT_SAMPLING_TYPE = "UPDATE_OMICS_SOIL_SEDIMENT_SAMPLING_TYPE";
  public static final String UPDATE_OMICS_ORGANIC_TISSUE_SAMPLING_TYPE = "UPDATE_OMICS_ORGANIC_TISSUE_SAMPLING_TYPE";
  public static final String UPDATE_OMICS_BARCODING_EXPECTED_ANALYSIS = "UPDATE_OMICS_BARCODING_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_GENOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_GENOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_TRANSCRIPTOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_TRANSCRIPTOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_PROTEOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_PROTEOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_METABOLOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_METABOLOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_EPIGENETICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_EPIGENETICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_OTHER_EXPECTED_ANALYSIS = "UPDATE_OMICS_OTHER_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_METABARCODING_EXPECTED_ANALYSIS = "UPDATE_OMICS_METABARCODING_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_METAGENOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_METAGENOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_METATRANSCRIPTOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_METATRANSCRIPTOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_METAPROTEOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_METAPROTEOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_METAMETABOLOMICS_EXPECTED_ANALYSIS = "UPDATE_OMICS_METAMETABOLOMICS_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_MICROBIOME_EXPECTED_ANALYSIS = "UPDATE_OMICS_MICROBIOME_EXPECTED_ANALYSIS";
  public static final String UPDATE_OMICS_ADDITIONAL_SAMPLING_INFORMATION = "UPDATE_OMICS_ADDITIONAL_SAMPLING_INFORMATION";
  public static final String UPDATE_OMICS_ADDITIONAL_SAMPLING_INFORMATION_ERROR = "UPDATE_OMICS_ADDITIONAL_SAMPLING_INFORMATION_ERROR";
  // Cruise Information
  public static final String UPDATE_CRUISE_TITLE = "UPDATE_CRUISE_TITLE";
  public static final String UPDATE_CRUISE_TITLE_ERROR = "UPDATE_CRUISE_TITLE_ERROR";
  public static final String UPDATE_CRUISE_PURPOSE = "UPDATE_CRUISE_PURPOSE";
  public static final String UPDATE_CRUISE_PURPOSE_ERROR = "UPDATE_CRUISE_PURPOSE_ERROR";
  public static final String UPDATE_CRUISE_DESCRIPTION = "UPDATE_CRUISE_DESCRIPTION";
  public static final String UPDATE_CRUISE_DESCRIPTION_ERROR = "UPDATE_CRUISE_DESCRIPTION_ERROR";
  public static final String UPDATE_DOCS_DIRECTORY = "UPDATE_DOCS_DIRECTORY";
  public static final String UPDATE_DOCS_DIRECTORY_ERROR = "UPDATE_DOCS_DIRECTORY_ERROR";

  // Datasets
  public static final String UPDATE_DATASET_LIST = "UPDATE_DATASET_LIST";
  public static final String UPDATE_DATASET_DATA_PREFIX = "UPDATE_DATASET_DATA_";

  private Events() {

  }

}
